# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user_db:
            entity: { class: AppBundle\Entity\User, property: username }

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                always_use_default_target_path: true
                default_target_path: /admin
            logout:
                path: logout
                target: login

        admin_area:
            pattern: ^/admin
            http_basic: ~
            provider: user_db

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
